# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190201_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproductdetails',
            old_name='cart_product_id',
            new_name='cart_product',
        ),
        migrations.RenameField(
            model_name='cartproductdetails',
            old_name='train_catefory',
            new_name='train_category',
        ),
        migrations.RenameField(
            model_name='cartproductpassengers',
            old_name='cart_product_id',
            new_name='cart_product',
        ),
        migrations.RenameField(
            model_name='cartproducts',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 2, 2), verbose_name='Date'),
        ),
    ]
