# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-03 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190202_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='sessionId',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 2, 3), verbose_name='Date'),
        ),
    ]
