# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sessionId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 2, 1), verbose_name='Date'),
        ),
    ]
